* AAPL Stock Project (.NET API and Blazor Server App)

** Dev environment
You may use Emacs or other editor for modifying the files (VS Code is
also OK). VS2022 works fine too.

1. Open folder or files to modify
2. Open powershell and navigate to project folder
3. Now run ~dotnet watch~ and follow instructions of next chapter for
   more info

   
You can you CMD, VS2022 shell, VSCode shell or any other shell too.

** .NET API
# On creation of empty API with sqlite:
# dotnet add package Microsoft.EntityFrameworkCore.Sqlite --version 8.0
# may need; dotnet tool install --global dotnet-ef
# dotnet add package Microsoft.EntityFrameworkCore.Design --version 8.0
# And then add namespaces to Program.cs (ef, migrations)
# dotnet ef migrations add InitialCreate
# or removal with: ef migrations remove
# dotnet ef database update

Start application with ~dotnet watch~

*** Sqlite and tools
For sqlite usage few dotnet packages and tools are needed:

#+begin_src 
dotnet add package Microsoft.EntityFrameworkCore.Sqlite --version 8.0
#+end_src

#+begin_src 
dotnet add package Microsoft.EntityFrameworkCore.Design --version 8.0  
#+end_src

#+begin_src 
dotnet tool install --global dotnet-ef  
#+end_src

#+begin_src 
dotnet ef migrations add InitialCreate  
#+end_src

#+begin_src 
dotnet ef database update  
#+end_src

If you wish, you can install Sqlite studio to manage the db:
https://sqlitestudio.pl/


** SpecFlow
The current version of SpecFlow does not support .NET 8.

This project uses another release of SpecFlow:
https://github.com/SpecFlowOSS/SpecFlow.VS/releases/tag/v2022.1.93-net8

** Readme comments
Readme file contains more info about creation steps of this project,
so you might want to inspect it more.

