apiVersion: v1
kind: Service
metadata:
  name: apple-stock-service
spec:
  selector:
    app: apple-stock-project-deployment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
